# Generated by Django 5.1.2 on 2024-10-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0005_comments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
