# Generated by Django 5.1.2 on 2024-10-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0006_comments_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('caption', models.TextField()),
            ],
        ),
    ]
