# Generated by Django 5.1.2 on 2024-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='man',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='operating_system',
            field=models.CharField(default='widows', max_length=25),
        ),
        migrations.AddField(
            model_name='users',
            name='owener',
            field=models.CharField(default='karim', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='women',
            field=models.BooleanField(default=True),
        ),
    ]
