# Generated by Django 5.1.2 on 2024-11-02 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0009_users_account_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 10, 30)),
        ),
    ]
