# Generated by Django 5.1.2 on 2024-11-02 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0010_users_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='users',
            name='operating_system',
            field=models.CharField(default='windows', max_length=25),
        ),
    ]
