# Generated by Django 5.1.2 on 2024-11-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0011_alter_users_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
