# Generated by Django 5.1.2 on 2024-11-05 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0012_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('man', models.BooleanField(default=False)),
                ('women', models.BooleanField(default=True)),
                ('owener', models.CharField(default='karim', max_length=50)),
                ('operating_system', models.CharField(default='windows', max_length=25)),
                ('account_problem', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
