# Generated by Django 5.1.2 on 2024-11-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0014_facebookaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='profile_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
